project/cmdb/cmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asset/', include('assetapp.urlsconf')),
]

project/cmdb/assetapp/models.py
from django.contrib.auth.models import User
from django.db import models


# *********** 1.总资产表 *********** #
class Asset(models.Model):
    '''所有资产的共有数据表'''
    ASSET_TYPE_CHOICE = (
        ('server', '服务器'),
        ('networkdevice', '网络设备'),
        ('storagedevice', '存储设备'),
        ('securitydevice', '安全设备'),
        ('software', '软件资产'),
    )

    ASSET_STATUS = (
        (0, '在线'),
        (1, '下线'),
        (2, '未知'),
        (3, '故障'),
        (4, '备用'),
    )

    asset_type = models.CharField(max_length=64, choices=ASSET_TYPE_CHOICE, default='server', verbose_name='资产类型')
    name = models.CharField(max_length=64, unique=True, verbose_name='资产名称')
    sn = models.CharField(max_length=128, unique=True, verbose_name='资产序列号')
    business_unit = models.ForeignKey(to='BusinessUnit', on_delete=models.SET_NULL, null=True, blank=True,
                                      verbose_name='所属业务线')
    status = models.PositiveSmallIntegerField(choices=ASSET_STATUS, default=0, verbose_name='设备状态')
    manufacturer = models.ForeignKey(to='Manufacturer', on_delete=models.SET_NULL, null=True, blank=True,
                                     verbose_name='制造商')
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    tags = models.ManyToManyField(to='Tag', blank=True, verbose_name='标签')
    admin = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True, blank=True,related_name='admin', verbose_name='资产管理员')
    idc = models.ForeignKey(to='IDC', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='所在机房')
    contract = models.ForeignKey(to='Contract', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='合同')
    purchase_date = models.DateField(null=True, blank=True, verbose_name='购买日期')
    expire_date = models.DateField(null=True, blank=True, verbose_name='过保日期')
    price = models.FloatField(null=True, blank=True, verbose_name='价格')
    approved_by = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True, blank=True,related_name='approved_by', verbose_name='批准人')
    memo = models.TextField(null=True, blank=True, verbose_name='备注')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '<%s>  %s' % (self.get_asset_type_display(), self.name)  # get_FOO_display()获得choice的描述

    class Meta:
        verbose_name = '总资产表'
        verbose_name_plural = '总资产表'
        ordering = ['-c_time']


# *********** 2.服务器表 *********** #
class Server(models.Model):
    '''服务器设备'''
    SUB_ASSET_TYPE_CHOICE = (
        (0, 'PC服务器'),
        (1, '刀片机'),
        (2, '小型机'),
    )

    CREATED_BY_CHOICE = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )

    asset = models.OneToOneField(to='Asset')  # 非常关键的一对一关联！
    sub_asset_type = models.PositiveSmallIntegerField(choices=SUB_ASSET_TYPE_CHOICE, default=0, verbose_name='服务器类型')
    created_by = models.CharField(max_length=32, choices=CREATED_BY_CHOICE, default='auto', verbose_name='添加方式')
    hosted_on = models.ForeignKey(to='self', null=True, blank=True, verbose_name='宿主机')  # 虚拟机专用字段
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='服务器型号')
    raid_type = models.CharField(max_length=512, null=True, blank=True, verbose_name='Raid类型')
    os_type = models.CharField(max_length=64, blank=True, null=True, verbose_name='操作系统类型')
    os_distribution = models.CharField(max_length=64, blank=True, null=True, verbose_name='发行版本')
    os_release = models.CharField(max_length=64, blank=True, null=True, verbose_name='操作系统版本')

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"


# *********** 3.安全设备表 *********** #
class SecurityDevice(models.Model):
    '''安全设备'''
    SUB_ASSET_TYPE_CHOICE = (
        (0, '防火墙'),
        (1, '入侵检测设备'),
        (2, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.PositiveSmallIntegerField(choices=SUB_ASSET_TYPE_CHOICE, default=0, verbose_name='安全设备类型')

    def __str__(self):
        return self.asset.name + '---' + self.get_sub_asset_type_display() + 'id:%s' % (self.id)

    class Meta:
        verbose_name = '安全设备'
        verbose_name_plural = "安全设备"


# *********** 4.存储设备表 *********** #
class StorageDevice(models.Model):
    '''存储设备'''
    SUB_ASSET_TYPE_CHOICE = (
        (0, '磁盘阵列'),
        (1, '网络存储器'),
        (2, '磁带库'),
        (4, '磁带机'),
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.PositiveSmallIntegerField(choices=SUB_ASSET_TYPE_CHOICE, default=0, verbose_name='存储设备类型')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + " id:%s" % (self.id)

    class Meta:
        verbose_name = '存储设备'
        verbose_name_plural = "存储设备"


# *********** 5.网络设备表 *********** #
class NetworkDevice(models.Model):
    '''网络设备'''
    SUB_ASSET_TYPE_CHOICE = (
        (0, '路由器'),
        (1, '交换机'),
        (2, '负载均衡'),
        (4, 'VPN设备'),
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.PositiveSmallIntegerField(choices=SUB_ASSET_TYPE_CHOICE, default=0, verbose_name="网络设备类型")
    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="VLanIP")
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="内网IP")
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name="网络设备型号")
    firmware = models.CharField(max_length=128, blank=True, null=True, verbose_name="设备固件版本")
    port_num = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="端口个数")
    device_detail = models.TextField(null=True, blank=True, verbose_name="详细配置")

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = "网络设备"


# *********** 6.软件表 *********** #
class Software(models.Model):
    '''只保存付费购买的软件'''
    SUB_ASSET_TYPE_CHOICE = (
        (0, '操作系统'),
        (1, '办公/开发软件'),
        (2, '业务软件'),
    )

    sub_asset_type = models.PositiveSmallIntegerField(choices=SUB_ASSET_TYPE_CHOICE, default=0, verbose_name="软件类型")
    license_num = models.IntegerField(default=1, verbose_name="授权数量")
    version = models.CharField(max_length=64, unique=True, help_text='例如: CentOS release 6.7 (Final)',
                               verbose_name='软件/系统版本')

    def __str__(self):
        return '%s--%s' % (self.get_sub_asset_type_display(), self.version)

    class Meta:
        verbose_name = '软件/系统'
        verbose_name_plural = "软件/系统"


# *********** 7.机房表 *********** #
class IDC(models.Model):
    """机房"""
    name = models.CharField(max_length=64, unique=True, verbose_name="机房名称")
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机房'
        verbose_name_plural = "机房"


# *********** 8.厂商表 *********** #
class Manufacturer(models.Model):
    """厂商"""
    name = models.CharField(max_length=64, unique=True, verbose_name='厂商名称')
    telephone = models.CharField(max_length=30, null=True, blank=True, verbose_name='支持电话')
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '厂商'
        verbose_name_plural = "厂商"


# *********** 9.业务线表 *********** #
class BusinessUnit(models.Model):
    """业务线"""
    parent_unit = models.ForeignKey('self', blank=True, null=True)
    name = models.CharField(max_length=64, unique=True, verbose_name='业务线')
    memo = models.CharField(max_length=64, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '业务线'
        verbose_name_plural = "业务线"


# *********** 10.合同表 *********** #
class Contract(models.Model):
    """合同"""
    sn = models.CharField(max_length=128, unique=True, verbose_name='合同号')
    name = models.CharField(max_length=128, verbose_name='合同名称')
    memo = models.TextField(blank=True, null=True, verbose_name='备注')
    price = models.IntegerField(verbose_name='合同金额')
    detail = models.TextField(blank=True, null=True, verbose_name='合同详细')
    start_day = models.DateField(blank=True, null=True, verbose_name='开始日期')
    end_day = models.DateField(blank=True, null=True, verbose_name='失效日期')
    license_num = models.IntegerField(blank=True, null=True, verbose_name='license数量')
    c_day = models.DateField(auto_now_add=True, verbose_name='创建日期')
    m_day = models.DateField(auto_now=True, verbose_name='修改日期')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '合同'
        verbose_name_plural = "合同"


# *********** 11.标签表 *********** #
class Tag(models.Model):
    """标签"""
    name = models.CharField(max_length=32, unique=True, verbose_name='标签名')
    c_day = models.DateField(auto_now_add=True, verbose_name='创建日期')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = "标签"


# *********** 12.CPU表 *********** #
class CPU(models.Model):
    """CPU组件"""
    asset = models.OneToOneField('Asset')  # 设备上的cpu肯定都是一样的，所以不需要建立多个cpu数据，一条就可以，因此使用一对一。
    cpu_model = models.CharField('CPU型号', max_length=128, blank=True, null=True)
    cpu_count = models.PositiveSmallIntegerField('物理CPU个数', default=1)
    cpu_core_count = models.PositiveSmallIntegerField('CPU核数', default=1)

    def __str__(self):
        return self.asset.name + ":  " + self.cpu_model

    class Meta:
        verbose_name = 'CPU'
        verbose_name_plural = "CPU"

project/cmdb/assetapp/views.py
import json

from assetapp import assetapp_handler_view
from assetapp import models
from assetapp.models import Asset
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt  # 忽略csrf post令牌
def report(request):
    if request.method == 'POST':
        asset_data = request.POST.get('asset_data', None)
        data = json.loads(asset_data)
        # 此处忽略了数据验证！
        if not data:
            return HttpResponse('没有数据！')
        if not isinstance(data, dict):
            return HttpResponse('数据必须为字典格式！')
        # 判断是否携带sn资产序列号,为真，进入审批流程
        sn = data.get('sn', None)
        if sn:
            # 首先判断是否在上线资产中存在该sn
            asset_obj = Asset.objects.filter(sn=sn)
            if asset_obj:
                # 进入已上线资产的数据更新流程
                update_asset = assetapp_handler_view.UpdateAsset(request, asset_obj[0], data)
                update_asset.asset_update()
                return HttpResponse('资产数据已经更新！')
            else:
                # asset_obj不存在，就更新或新建
                asset_new = assetapp_handler_view.NewAsset(request, data)
                resp = asset_new.add_to_new_assets_zone()
                return HttpResponse(resp)
        else:
            return HttpResponse('没有该资产序列号，请检查数据！')


# 资产总表，表格的形式展示资产信息
def index(request):
    assets = models.Asset.objects.all()
    return render(request=request, template_name='assetapp/index.html', context=locals())


# 仪表盘，图形化的数据展示
def dashboard(request):
    asset_obj=models.Asset.objects
    total=asset_obj.count()
    upline=asset_obj.filter(status=0).count()       # 在线
    offline=asset_obj.filter(status=1).count()      # 下线
    unknown =asset_obj.filter(status=2).count()     # 未知
    breakdown =asset_obj.filter(status=3).count()   # 故障
    backup =asset_obj.filter(status=4).count()      # 备用
    up_rate=round(upline/total*100)
    o_rate=round(offline/total*100)
    un_rate=round(unknown/total*100)
    bd_rate=round(breakdown/total*100)
    bu_rate=round(backup/total*100)

    server_number=models.Server.objects.count()
    networkdevice_number=models.NetworkDevice.objects.count()
    storagedevice_number=models.StorageDevice.objects.count()
    securitydevice_number=models.SecurityDevice.objects.count()
    software_number=models.Software.objects.count()

    return render(request, template_name='assetapp/dashboard.html', context=locals())


# 单个资产的详细信息页面
def detail(request, asset_id):
    """以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。"""
    asset = get_object_or_404(models.Asset, id=asset_id)
    return render(request, 'assetapp/detail.html', context=locals())

project/cmdb/templates/assetapp/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}资产详细{% endblock %}
{% block css %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产详细
        <small>asset info</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'assetapp:dashboard' %}"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li><a href="{% url 'assetapp:index' %}">资产总表</a></li>
        <li class="active">资产详细</li>
      </ol>
    </section>

<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">资产：{{ asset.name }}</strong></h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
            <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN序列号</th>
                        <th>业务线</th>
                        <th>制造商</th>
                        <th>管理IP</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_asset_type_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td>{{ asset.business_unit|default:'-' }}</td>
                    <td>{{ asset.manufacturer|default:'-' }}</td>
                    <td>{{ asset.manage_ip|default:'-' }}</td>
                    <td>{{ asset.idc|default:'-' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <br />
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                    <tr>
                        <th>合同</th>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.contract.name|default:'-' }}</td>
                    <td>{{ asset.price|default:'-' }}</td>
                    <td>{{ asset.purchase_date|default:'-' }}</td>
                    <td>{{ asset.expire_date|default:'-' }}</td>
                    <td>{{ asset.admin|default:'-' }}</td>
                    <td>{{ asset.approved_by|default:'-' }}</td>
                    <td>{{ asset.memo|default:'-' }}</td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <h4><b>服务器:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>型号</th>
                        <th>宿主机</th>
                        <th>Raid类型</th>
                        <th>OS类型</th>
                        <th>OS发行版本</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.server.get_sub_asset_type_display }}</td>
                    <td>{{ asset.server.model|default:'-' }}</td>
                    <td>{{ asset.server.hosted_on.id|default:'-' }}</td>
                    <td>{{ asset.server.raid_type|default:'-' }}</td>
                    <td>{{ asset.server.os_type|default:'-' }}</td>
                    <td>{{ asset.server.os_distribution|default:'-' }}</td>
                    <td>{{ asset.server.os_release|default:'-' }}</td>
                    <td>{{ asset.server.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>
            <h4><b>CPU:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid purple;border-bottom:1px solid purple">
                <thead>
                    <tr>
                        <th  style="width: 45%">CPU型号</th>
                        <th  style="width: 15%">物理CPU个数</th>
                        <th>CPU核数</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.cpu.cpu_model|default:'-' }}</td>
                    <td>{{ asset.cpu.cpu_count|default:'1' }}</td>
                    <td>{{ asset.cpu.cpu_core_count|default:'1' }}</td>
                </tr>
                </tbody>
            </table>
        <h4><b>内存:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid orangered;border-bottom:1px solid orangered">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for ram in asset.ram_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ ram.model|default:'-' }}</td>
                        <td>{{ ram.capacity|default:'-' }}</td>
                        <td>{{ ram.slot }}</td>
                        <td>{{ ram.manufacturer|default:'-' }}</td>
                        <td>{{ ram.sn|default:'-' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <h4><b>硬盘:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid brown;border-bottom:1px solid brown">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>接口类型</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for disk in asset.disk_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ disk.model|default:'-' }}</td>
                        <td>{{ disk.capacity|default:'-' }}</td>
                        <td>{{ disk.slot|default:'-'  }}</td>
                        <td>{{ disk.get_interface_type_display }}</td>
                        <td>{{ disk.manufacturer|default:'-' }}</td>
                        <td>{{ disk.sn}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <h4><b>网卡:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid #a59b1a;border-bottom:1px solid #a59b1a">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>名称</th>
                        <th>型号</th>
                        <th>MAC</th>
                        <th>IP</th>
                        <th>掩码</th>
                        <th>绑定地址</th>
                    </tr>
                </thead>
                <tbody>
                {% for nic in asset.nic_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ nic.name|default:'-' }}</td>
                        <td>{{ nic.model }}</td>
                        <td>{{ nic.mac  }}</td>
                        <td>{{ nic.ip_address|default:'-' }}</td>
                        <td>{{ nic.net_mask|default:'-' }}</td>
                        <td>{{ nic.bonding|default:'-' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assetapp:index' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
    </div>
</section>
{% endblock %}

{% block script %}
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- page script -->
{% endblock %}